project_id = "agsgsdjobfpodjneknpm"

[functions.update-asset-prices]
verify_jwt = false

[functions.generate-news]
verify_jwt = true

[functions.manage-daily-challenges]
verify_jwt = true

[functions.process-dividends]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-feedback]
verify_jwt = false
